name: native_template_generator
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.1.1
  source_gen: ^1.1.1
  analyzer: ^2.6.0
  string_scanner: ^1.1.0
  code_builder: ^4.1.0
  built_collection: ^5.1.1
  collection: ^1.15.0-nullsafety.4
  native_template_support:
    git:
      url: https://github.com/radzish/native_template.git
      path: native_template_support

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.18.2
  build_runner: ^2.1.4

dependency_overrides:
  native_template_support:
    path: ../native_template_support
